[package]
name = "metalife_wasm"
version = "0.1.0"
edition = "2021"
description = "WASM core engine for MetaLife artificial life simulation"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
